# Generated by Django 4.1.4 on 2022-12-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='register',
            managers=[
            ],
        ),
    ]
